-- ── lineup ──────────────────────────────────────────────────────────────────
CREATE TABLE public.lineup (
    lineup_id   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id    bigint    NOT NULL REFERENCES public.events(event_id)  ON DELETE CASCADE,
    team_id     bigint    NOT NULL REFERENCES public.teams(team_id)    ON DELETE CASCADE,
    squad_id    bigint             REFERENCES public.squads(squad_id)  ON DELETE SET NULL,
    format      smallint  NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now()
);

-- ── lineup_details ───────────────────────────────────────────────────────────
CREATE TABLE public.lineup_details (
    lineup_detail_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lineup_id        bigint   NOT NULL REFERENCES public.lineup(lineup_id)   ON DELETE CASCADE,
    member_id        bigint   NOT NULL REFERENCES public.members(member_id)  ON DELETE CASCADE,
    position_num     smallint NOT NULL,  -- 1–15 for starters, 1–5 for subs
    is_sub           boolean  NOT NULL DEFAULT false,
    created_at       timestamptz NOT NULL DEFAULT now()
);

-- ── indexes ──────────────────────────────────────────────────────────────────
CREATE INDEX idx_lineup_event_id  ON public.lineup(event_id);
CREATE INDEX idx_lineup_team_id   ON public.lineup(team_id);
CREATE INDEX idx_lineup_details_lineup_id ON public.lineup_details(lineup_id);

-- ── RLS ──────────────────────────────────────────────────────────────────────
ALTER TABLE public.lineup         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lineup_details ENABLE ROW LEVEL SECURITY;

-- Authenticated users can read and insert lineups
-- (team-membership guard will be added as part of the wider security hardening)
CREATE POLICY "authenticated_read_lineup"
    ON public.lineup FOR SELECT TO authenticated USING (true);

CREATE POLICY "authenticated_insert_lineup"
    ON public.lineup FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "authenticated_read_lineup_details"
    ON public.lineup_details FOR SELECT TO authenticated USING (true);

CREATE POLICY "authenticated_insert_lineup_details"
    ON public.lineup_details FOR INSERT TO authenticated WITH CHECK (true);
